apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels: 
    tier: frontend
spec: 
  selector:
    matchLabels:
      app: myapp
  replicas: 6
  template:
    metadata: 
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
          # resources:
          #   requests:
          #     memory: "50M"
          #   limits:
          #     memory: "100M"
          #     cpu: "500Mi"