apiVersion: v1
kind: Pod
metadata: 
  name: nginx-2
  labels:
    app: myapp
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "50M"
        limits:
          memory: "128Mi"
          cpu: "500Mi"